### ISSUE TITLE
API Reference options

### ISSUE THREAD

**Issue by Fredwared** [matejsvajger/laravel-mix-pug#3]
Hi. How to overide reference options? pretty, filename etc. Thanks.
-----
I've tried use third option `locals: { pretty: true } ; {pretty: true}`   but doesnt work.

**Comment by juniorgarcia** [comment]
Same here. It does not seem that it's possible to override the Pug variables itself.

**Comment by matejsvajger** [comment]
It's possible now to modify pug api via `pug` key in options object:

f5e11c8fcc9874756a4746d7174886b1ec58b372
