### ISSUE TITLE
deprecated dependency on gulp-util

### ISSUE THREAD

**Issue by sandbernar** [matejsvajger/laravel-mix-pug#8]
└─┬ laravel-mix-pug@0.2.1
  └─┬ laravel-mix@1.7.2
    └─┬ img-loader@2.0.1
      └─┬ imagemin-gifsicle@5.2.0
        └─┬ gifsicle@3.0.4
          └─┬ bin-build@2.2.0
            └─┬ download@4.4.3
              └─┬ gulp-decompress@1.2.0
                └── gulp-util@3.0.8

**Comment by oliverquynh** [comment]
I think nobody can help you with too little information.
