### ISSUE TITLE
laravel-mix Mix.addTask is removed

### ISSUE THREAD

**Issue by vpapaloukas** [matejsvajger/laravel-mix-pug#9]
laravel-mix with commit [Remove custom asset handling](https://github.com/JeffreyWay/laravel-mix/commit/3e635df9fef1bcd5c1f34ed3e1fc51970804d3c7#diff-ee68988ce000eda7b5b11a8985aa3d5c) causes plugin to error on Mix.addAsset as it is removed.

Can there be a workaround on how the plugin will function without using addAsset?

**Comment by dsktschy** [comment]
I submitted a pull request to resolve this issue.
https://github.com/matejsvajger/laravel-mix-pug/pull/10

Assets are added in this part, so Mix.addAsset is not needed.
https://github.com/JeffreyWay/laravel-mix/blob/9acd47220fd671f2b317ccc4b109ad06b5ea78da/src/webpackPlugins/CustomTasksPlugin.js#L37

**Comment by matejsvajger** [comment]
#10 merged and released a new version **0.3.0** that adds support for laravel-mix v4.
